### ISSUE TITLE
Read.me

### ISSUE THREAD

**Issue by MarcialSanchis-Agudo** [ArnauMiro/pyLowOrder#49]
One paranthesis missing on the reference, please find below the correct input for the .bib in   latex 
@ArnauMiro .

@misc{pyLOM,
  author    = {Eiximeno, Benet and Begiashvili, Beka and Miro, Arnau and Valero, Eusebio and Lehmkuhl, Oriol},
  title     = {pyLOM: Low order modelling in python},
  year      = {2022},
  publisher = {Barcelona Supercomputing Center},
  journal   = {GitHub repository},
  url       = {https://github.com/ArnauMiro/UPM_BSC_LowOrder},
}

**Comment by ArnauMiro** [comment]
Thanks @MarcialSanchis-Agudo 

I've already fixed it on the Wiki and on the develop branch. It will fix on main on our next merge.
